//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeppelinWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zeppelin
    {
        public int ZeppelinId { get; set; }
        public string ZeppelinNumber { get; set; }
        public string ZeppelinImage { get; set; }
        public decimal ZeppelinPrice { get; set; }
        public int BookingStatusId { get; set; }
        public int SeatTypeId { get; set; }
        public int ZeppelinCapacity { get; set; }
        public string ZeppelinFrom { get; set; }
        public string ZeppelinTo { get; set; }
        public bool IsActive { get; set; }
    }
}
